/// Code map generation: ranked file signatures for context injection.
use crate::{db, parser};
use anyhow::Result;
use std::path::Path;

pub fn run_map(root: &Path, tokens: usize, format: &str) -> Result<()> {
    let db_path = root.join(".codemap/index.db");
    if !db_path.exists() {
        anyhow::bail!("No index found. Run `codemap index` first.");
    }
    let conn = db::init_db(
        db_path
            .to_str()
            .ok_or_else(|| anyhow::anyhow!("non-UTF-8 database path"))?,
    )?;

    // Load all ranked files (generous limit, we'll trim by token budget)
    let files = db::get_ranked_files(&conn, 500)?;
    if files.is_empty() {
        eprintln!("codemap: index is empty");
        return Ok(());
    }

    let output = generate_map(root, &conn, &files, tokens, format)?;
    print!("{output}");
    Ok(())
}

/// Generate the map string (also used by MCP server).
pub fn generate_map(
    root: &Path,
    conn: &rusqlite::Connection,
    files: &[db::RankedFile],
    tokens: usize,
    format: &str,
) -> Result<String> {
    let char_budget = tokens * 4; // ~4 chars per token
    let mut output = String::new();
    let mut chars_used = 0usize;

    match format {
        "json" => {
            return generate_json_map(root, files, char_budget);
        }
        _ => {
            // tree format
            output.push_str("## Repository Code Map (auto-generated by codemap)\n");
            let header = "Showing top files by structural importance (PageRank).\n\n";
            output.push_str(header);
            chars_used += output.len();

            for file in files {
                if chars_used >= char_budget {
                    break;
                }

                let abs_path = root.join(&file.path);
                let source = match std::fs::read_to_string(&abs_path) {
                    Ok(s) => s,
                    Err(_) => continue,
                };

                let signatures = parser::extract_signatures(&abs_path, &source);
                if signatures.is_empty() {
                    continue;
                }

                // Build file entry
                let mut entry = format!("{}:\n", file.path);
                for sig in &signatures {
                    entry.push_str(&format!("  {sig}\n"));
                }

                // Check imports for this file
                if let Ok(deps) = db::get_file_deps(conn, &file.path, "imports")
                    && !deps.is_empty()
                {
                    let shown: Vec<&str> =
                        deps.iter().map(|d| d.file_path.as_str()).take(5).collect();
                    entry.push_str(&format!("  → imports: {}\n", shown.join(", ")));
                }
                entry.push('\n');

                if chars_used + entry.len() > char_budget {
                    break;
                }
                chars_used += entry.len();
                output.push_str(&entry);
            }
        }
    }

    Ok(output)
}

fn generate_json_map(root: &Path, files: &[db::RankedFile], char_budget: usize) -> Result<String> {
    let mut entries = Vec::new();
    let mut chars_used = 0usize;

    for file in files {
        if chars_used >= char_budget {
            break;
        }

        let abs_path = root.join(&file.path);
        let source = match std::fs::read_to_string(&abs_path) {
            Ok(s) => s,
            Err(_) => continue,
        };

        let signatures = parser::extract_signatures(&abs_path, &source);
        let entry = serde_json::json!({
            "path": file.path,
            "rank": file.rank,
            "signatures": signatures,
        });
        let entry_str = serde_json::to_string(&entry)?;
        chars_used += entry_str.len();
        entries.push(entry);
    }

    let output = serde_json::to_string_pretty(&entries)?;
    Ok(output)
}
